export const states = {
  'USA': [
    'California', 'New York', 'Texas', 'Florida', 'Illinois',
    'Pennsylvania', 'Ohio', 'Georgia', 'North Carolina', 'Michigan',
    'New Jersey', 'Virginia', 'Washington', 'Arizona', 'Massachusetts',
    'Tennessee', 'Indiana', 'Missouri', 'Maryland', 'Wisconsin',
    'Colorado', 'Minnesota', 'South Carolina', 'Alabama', 'Louisiana',
    'Kentucky', 'Oregon', 'Oklahoma', 'Connecticut', 'Iowa',
    'Mississippi', 'Arkansas', 'Kansas', 'Nevada', 'Utah',
    'Nebraska', 'West Virginia', 'Idaho', 'Hawaii', 'Maine',
    'New Hampshire', 'Rhode Island', 'Montana', 'Wyoming', 'Delaware',
    'South Dakota', 'North Dakota', 'Alaska', 'Vermont', 'New Mexico'
  ],
  'India': [
    'Delhi', 'Maharashtra', 'Karnataka', 'Tamil Nadu', 'West Bengal',
    'Uttar Pradesh', 'Gujarat', 'Rajasthan', 'Punjab', 'Haryana',
    'Bihar', 'Jharkhand', 'Assam', 'Odisha', 'Kerala',
    'Telangana', 'Andhra Pradesh', 'Madhya Pradesh', 'Chhattisgarh', 'Himachal Pradesh',
    'Uttarakhand', 'Goa', 'Sikkim', 'Arunachal Pradesh', 'Nagaland',
    'Manipur', 'Tripura', 'Meghalaya', 'Mizoram', 'Nagaland',
    'Puducherry', 'Ladakh', 'Lakshadweep', 'Dadra and Nagar Haveli', 'Daman and Diu'
  ]
};

export const cities = {
  'California': ['Los Angeles', 'San Francisco', 'San Diego', 'San Jose', 'Sacramento'],
  'New York': ['New York City', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse'],
  'Texas': ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth'],
  'Florida': ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'St. Petersburg'],
  'Illinois': ['Chicago', 'Aurora', 'Naperville', 'Joliet', 'Elgin'],
  'Pennsylvania': ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading'],
  'Ohio': ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron'],
  'Georgia': ['Atlanta', 'Augusta', 'Columbus', 'Macon', 'Savannah'],
  'North Carolina': ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem'],
  'Michigan': ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Ann Arbor'],
  'New Jersey': ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Edison'],
  'Virginia': ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Arlington'],
  'Washington': ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'],
  'Arizona': ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale'],
  'Massachusetts': ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell'],
  'Tennessee': ['Memphis', 'Nashville', 'Knoxville', 'Chattanooga', 'Jackson'],
  'Indiana': ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel'],
  'Missouri': ['Kansas City', 'St. Louis', 'Springfield', 'Columbia', 'Jefferson City'],
  'Maryland': ['Baltimore', 'Frederick', 'Rockville', 'Bowie', 'Gaithersburg'],
  'Wisconsin': ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine'],
  'Colorado': ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood'],
  'Minnesota': ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth', 'Bloomington'],
  'South Carolina': ['Charleston', 'Columbia', 'Greenville', 'Myrtle Beach', 'Spartanburg'],
  'Alabama': ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville', 'Tuscaloosa'],
  'Louisiana': ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles'],
  'Kentucky': ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington'],
  'Oregon': ['Portland', 'Salem', 'Eugene', 'Gresham', 'Hillsboro'],
  'Oklahoma': ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond'],
  'Connecticut': ['Bridgeport', 'New Haven', 'Stamford', 'Hartford', 'Waterbury'],
  'Iowa': ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City'],
  'Mississippi': ['Jackson', 'Gulfport', 'Biloxi', 'Southaven', 'Hattiesburg'],
  'Arkansas': ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale', 'Jonesboro'],
  'Kansas': ['Wichita', 'Overland Park', 'Kansas City', 'Olathe', 'Topeka'],
  'Nevada': ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks'],
  'Utah': ['Salt Lake City', 'Provo', 'West Valley City', 'Ogden', 'St. George'],
  'Nebraska': ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney'],
  'West Virginia': ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg', 'Wheeling'],
  'Idaho': ['Boise', 'Nampa', 'Meridian', 'Idaho Falls', 'Pocatello'],
  'Hawaii': ['Honolulu', 'Hilo', 'Kailua', 'Kapolei', 'Waipahu'],
  'Maine': ['Portland', 'Lewiston', 'Bangor', 'Augusta', 'Biddeford'],
  'New Hampshire': ['Manchester', 'Nashua', 'Concord', 'Derry', 'Keene'],
  'Rhode Island': ['Providence', 'Warwick', 'Cranston', 'Pawtucket', 'East Providence'],
  'Montana': ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Butte'],
  'Wyoming': ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Jackson'],
  'Delaware': ['Wilmington', 'Dover', 'Newark', 'Middletown', 'Georgetown'],
  'South Dakota': ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Mitchell', 'Pierre'],
  'North Dakota': ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo'],
  'Alaska': ['Anchorage', 'Juneau', 'Fairbanks', 'Wasilla', 'Sitka'],
  'Vermont': ['Burlington', 'South Burlington', 'Rutland', 'Barre', 'Montpelier'],
  'New Mexico': ['Albuquerque', 'Santa Fe', 'Las Cruces', 'Rio Rancho', 'Roswell'],
  'Delhi': ['New Delhi', 'Old Delhi', 'Delhi Cantonment', 'Connaught Place', 'Karol Bagh'],
  'Maharashtra': ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Aurangabad'],
  'Karnataka': ['Bangalore', 'Mysore', 'Hubli', 'Dharwad', 'Mangalore'],
  'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem'],
  'West Bengal': ['Kolkata', 'Siliguri', 'Asansol', 'Durgapur', 'Howrah'],
  'Uttar Pradesh': ['Lucknow', 'Kanpur', 'Agra', 'Varanasi', 'Allahabad'],
  'Gujarat': ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Gandhinagar'],
  'Rajasthan': ['Jaipur', 'Udaipur', 'Kota', 'Jodhpur', 'Bikaner'],
  'Punjab': ['Chandigarh', 'Amritsar', 'Jalandhar', 'Ludhiana', 'Patiala'],
  'Haryana': ['Gurgaon', 'Faridabad', 'Karnal', 'Ambala', 'Hisar'],
  'Bihar': ['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Arrah'],
  'Jharkhand': ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Hazaribagh'],
  'Assam': ['Guwahati', 'Silchar', 'Dibrugarh', 'Jorhat', 'Nagaon'],
  'Odisha': ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Sambalpur', 'Berhampur'],
  'Kerala': ['Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Kannur', 'Alappuzha'],
  'Telangana': ['Hyderabad', 'Warangal', 'Nizamabad', 'Khammam', 'Karimnagar'],
  'Andhra Pradesh': ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Tirupati', 'Kakinada'],
  'Madhya Pradesh': ['Bhopal', 'Indore', 'Gwalior', 'Jabalpur', 'Ujjain'],
  'Chhattisgarh': ['Raipur', 'Bilaspur', 'Durg', 'Korba', 'Rajnandgaon'],
  'Himachal Pradesh': ['Shimla', 'Dharamshala', 'Kullu', 'Manali', 'Solan'],
  'Uttarakhand': ['Dehradun', 'Haridwar', 'Nainital', 'Rishikesh', 'Roorkee'],
  'Goa': ['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda'],
  'Sikkim': ['Gangtok', 'Namchi', 'Pelling', 'Jorethang', 'Rangpo'],
  'Arunachal Pradesh': ['Itanagar', 'Tawang', 'Naharlagun', 'Pasighat', 'Ziro'],
  'Nagaland': ['Kohima', 'Dimapur', 'Mokokchung', 'Wokha', 'Tuensang'],
  'Manipur': ['Imphal', 'Thoubal', 'Churachandpur', 'Kakching', 'Jiribam'],
  'Tripura': ['Agartala', 'Unakoti', 'Dhalai', 'Khowai', 'Sepahijala'],
  'Meghalaya': ['Shillong', 'Tura', 'Jowai', 'Nongpoh', 'Mairang'],
  'Mizoram': ['Aizawl', 'Lunglei', 'Saiha', 'Champhai', 'Kolasib'],
  'Puducherry': ['Puducherry', 'Karaikal', 'Mahe', 'Yanam'],
  'Ladakh': ['Leh', 'Kargil'],
  'Lakshadweep': ['Kavaratti', 'Minicoy', 'Agatti'],
  'Dadra and Nagar Haveli': ['Silvassa'],
  'Daman and Diu': ['Daman', 'Diu']
};
